// TPOS Attributes from TPOS system - Using new variant generator data structure
export const TPOS_ATTRIBUTES = {
  sizeText: [
    { Id: 5, Name: "Free Size", Code: "FS", Sequence: null },
    { Id: 1, Name: "S", Code: "S", Sequence: null },
    { Id: 2, Name: "M", Code: "M", Sequence: null },
    { Id: 3, Name: "L", Code: "L", Sequence: null },
    { Id: 4, Name: "XL", Code: "XL", Sequence: null },
    { Id: 31, Name: "XXL", Code: "xxl", Sequence: null },
    { Id: 32, Name: "XXXL", Code: "xxxl", Sequence: null },
  ],
  color: [
    { Id: 6, Name: "Trắng", Code: "trang", Sequence: null },
    { Id: 7, Name: "Đen", Code: "den", Sequence: null },
    { Id: 8, Name: "Đỏ", Code: "do", Sequence: null },
    { Id: 9, Name: "Vàng", Code: "vang", Sequence: null },
    { Id: 10, Name: "Cam", Code: "cam", Sequence: null },
    { Id: 11, Name: "Xám", Code: "xam", Sequence: null },
    { Id: 12, Name: "Hồng", Code: "hong", Sequence: null },
    { Id: 14, Name: "Nude", Code: "nude", Sequence: null },
    { Id: 15, Name: "Nâu", Code: "nau", Sequence: null },
    { Id: 16, Name: "Rêu", Code: "reu", Sequence: null },
    { Id: 17, Name: "Xanh", Code: "xanh", Sequence: null },
    { Id: 25, Name: "Bạc", Code: "bac", Sequence: null },
    { Id: 26, Name: "Tím", Code: "tim", Sequence: null },
    { Id: 27, Name: "Xanh Min", Code: "xanhmin", Sequence: null },
    { Id: 28, Name: "Trắng Kem", Code: "trangkem", Sequence: null },
    { Id: 29, Name: "Xanh Lá", Code: "xanhla", Sequence: null },
    { Id: 38, Name: "Cổ Vịt", Code: "co vit", Sequence: null },
    { Id: 40, Name: "Xanh Đậu", Code: "xanh dau", Sequence: null },
    { Id: 42, Name: "Tím Môn", Code: "timmon", Sequence: null },
    { Id: 43, Name: "Muối Tiêu", Code: "muoitieu", Sequence: null },
    { Id: 45, Name: "Kem", Code: "kem", Sequence: null },
    { Id: 47, Name: "Hồng Đậm", Code: "hongdam", Sequence: null },
    { Id: 49, Name: "Ghi", Code: "ghi", Sequence: null },
    { Id: 50, Name: "Xanh Mạ", Code: "xanhma", Sequence: null },
    { Id: 51, Name: "Vàng Đồng", Code: "vangdong", Sequence: null },
    { Id: 52, Name: "Xanh Bơ", Code: "xanhbo", Sequence: null },
    { Id: 53, Name: "Xanh Đen", Code: "xanhden", Sequence: null },
    { Id: 54, Name: "Xanh CoBan", Code: "xanhcoban", Sequence: null },
    { Id: 55, Name: "Xám Đậm", Code: "xamdam", Sequence: null },
    { Id: 56, Name: "Xám Nhạt", Code: "xamnhat", Sequence: null },
    { Id: 57, Name: "Xanh Dương", Code: "xanhduong", Sequence: null },
    { Id: 58, Name: "Cam Sữa", Code: "camsua", Sequence: null },
    { Id: 59, Name: "Hồng Nhạt", Code: "hongnhat", Sequence: null },
    { Id: 60, Name: "Đậm", Code: "dam", Sequence: null },
    { Id: 61, Name: "Nhạt", Code: "nhat", Sequence: null },
    { Id: 62, Name: "Xám Khói", Code: "xamkhoi", Sequence: null },
    { Id: 63, Name: "Xám Chuột", Code: "xamchuot", Sequence: null },
    { Id: 64, Name: "Xám Đen", Code: "xamden", Sequence: null },
    { Id: 65, Name: "Xám Trắng", Code: "xamtrang", Sequence: null },
    { Id: 66, Name: "Xanh Đậm", Code: "xanhdam", Sequence: null },
    { Id: 67, Name: "Sọc Đen", Code: "socden", Sequence: null },
    { Id: 68, Name: "Sọc Trắng", Code: "soctrang", Sequence: null },
    { Id: 69, Name: "Sọc Xám", Code: "socxam", Sequence: null },
    { Id: 70, Name: "Jean Trắng", Code: "jeantrang", Sequence: null },
    { Id: 71, Name: "Jean Xanh", Code: "jeanxanh", Sequence: null },
    { Id: 72, Name: "Cam Đất", Code: "camdat", Sequence: null },
    { Id: 73, Name: "Nâu Đậm", Code: "naudam", Sequence: null },
    { Id: 74, Name: "Nâu Nhạt", Code: "naunhat", Sequence: null },
    { Id: 75, Name: "Đỏ Tươi", Code: "dotuoi", Sequence: null },
    { Id: 76, Name: "Đen Vàng", Code: "denvang", Sequence: null },
    { Id: 77, Name: "Cà Phê", Code: "caphe", Sequence: null },
    { Id: 78, Name: "Đen Bạc", Code: "denbac", Sequence: null },
    { Id: 79, Name: "Bò", Code: "bo", Sequence: null },
    { Id: 82, Name: "Sọc Xanh", Code: "socxanh", Sequence: null },
    { Id: 83, Name: "Xanh Rêu", Code: "xanhreu", Sequence: null },
    { Id: 84, Name: "Hồng Ruốc", Code: "hongruoc", Sequence: null },
    { Id: 85, Name: "Hồng Dâu", Code: "hongdau", Sequence: null },
    { Id: 86, Name: "Xanh Nhạt", Code: "xanhnhat", Sequence: null },
    { Id: 87, Name: "Xanh Ngọc", Code: "xanhngoc", Sequence: null },
    { Id: 88, Name: "Caro", Code: "caro", Sequence: null },
    { Id: 89, Name: "Sọc Hồng", Code: "sochong", Sequence: null },
    { Id: 90, Name: "Trong", Code: "trong", Sequence: null },
    { Id: 95, Name: "Trắng Hồng", Code: "tranghong", Sequence: null },
    { Id: 96, Name: "Trắng Sáng", Code: "trangsang", Sequence: null },
    { Id: 97, Name: "Đỏ Đô", Code: "dodo", Sequence: null },
    { Id: 98, Name: "Cam Đào", Code: "camdao", Sequence: null },
    { Id: 99, Name: "Cam Lạnh", Code: "camlanh", Sequence: null },
    { Id: 100, Name: "Hồng Đào", Code: "hongdao", Sequence: null },
    { Id: 101, Name: "Hồng Đất", Code: "hongdat", Sequence: null },
    { Id: 102, Name: "Tím Đậm", Code: "timdam", Sequence: null },
    { Id: 103, Name: "SỌC ĐỎ", Code: "socdo", Sequence: null },
    { Id: 104, Name: "SỌC NÂU", Code: "socnau", Sequence: null },
    { Id: 105, Name: "Sọc Trắng To", Code: "soctrangto", Sequence: null },
  ],
  sizeNumber: [
    { Id: 22, Name: "1", Code: "1", Sequence: null },
    { Id: 23, Name: "2", Code: "2", Sequence: null },
    { Id: 24, Name: "3", Code: "3", Sequence: null },
    { Id: 48, Name: "4", Code: "4", Sequence: null },
    { Id: 80, Name: "27", Code: "27", Sequence: null },
    { Id: 81, Name: "28", Code: "28", Sequence: null },
    { Id: 18, Name: "29", Code: "29", Sequence: null },
    { Id: 19, Name: "30", Code: "30", Sequence: null },
    { Id: 20, Name: "31", Code: "31", Sequence: null },
    { Id: 21, Name: "32", Code: "32", Sequence: null },
    { Id: 46, Name: "34", Code: "34", Sequence: null },
    { Id: 33, Name: "35", Code: "35", Sequence: null },
    { Id: 34, Name: "36", Code: "36", Sequence: null },
    { Id: 35, Name: "37", Code: "37", Sequence: null },
    { Id: 36, Name: "38", Code: "38", Sequence: null },
    { Id: 37, Name: "39", Code: "39", Sequence: null },
    { Id: 44, Name: "40", Code: "40", Sequence: null },
    { Id: 91, Name: "41", Code: "41", Sequence: null },
    { Id: 92, Name: "42", Code: "42", Sequence: null },
    { Id: 93, Name: "43", Code: "43", Sequence: null },
    { Id: 94, Name: "44", Code: "44", Sequence: null },
  ]
};

export const DEFAULT_SELECTIONS = {
  sizeText: ["M", "L", "XL", "XXL", "XXXL"],
  color: ["Cam", "Xanh Đậu", "Xanh Đen"],
  sizeNumber: ["29", "30", "32"]
};

// ============================================
// EXPORT FOR VARIANT GENERATOR COMPATIBILITY
// ============================================

export const TPOS_ATTRIBUTES_DATA = {
  ATTRIBUTES: [
    { Id: 1, Name: "Size Chữ", Code: "SZCh" },
    { Id: 3, Name: "Màu", Code: "Mau" },
    { Id: 4, Name: "Size Số", Code: "SZNu" },
  ],

  ATTRIBUTE_VALUES: {
    1: TPOS_ATTRIBUTES.sizeText,    // 7 items
    3: TPOS_ATTRIBUTES.color,       // 68 items ✅ FULL DATA
    4: TPOS_ATTRIBUTES.sizeNumber,  // 21 items
  }
};
